name: jomblo_locator
description: A new Flutter project for finding jomblo nearby.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.0
  geolocator: ^10.4.0
  google_maps_flutter: ^2.5.0
  provider: ^6.1.1

flutter:
  uses-material-design: true
